#!/usr/bin/env python3

# Problem 2:
#     Each new term in the Fibonacci sequence is generated by adding the
#     previous two terms. By starting with 1 and 2, the first 10 terms will be:
#         1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#     By considering the terms in the Fibonacci sequence whose values do not
#     exceed four million, find the sum of the even-valued terms.
# Answer:
#     4613732
# Notes:
#     - Compute only the even-valued terms.

def problem2(n):
    vsum = 2
    prev = 2
    value = 8
    while value <= n:
        vsum += value
        tmp = value
        value = 4 * value + prev
        prev = tmp

    return vsum

# print(problem2(4000000))
